### PR TITLE
fix: typos in documentation files

### PR DESCRIPTION
**Pull request by leopardracer**
This pull request contains changes to improve clarity, correctness and structure.

Description correction:
Corrected "Gerneated" to "Generated".

Please review the changes and let me know if any additional changes are needed.

### CODE REVIEW

**Comment by leopardracer** [comment]
@shazow Hi! Apologies for the inconvenience. I just wanted to check if there’s anything I can improve in my pull request. Please feel free to ask any questions or let me know if any changes are needed to meet the project's merge requirements. I’m happy to make adjustments!

**Comment by shazow** [comment]
@leopardracer I'm not a maintainer here. :)

**Comment by leopardracer** [comment]
> a

oh, sorry... maybe you know someone who could give me some advice?

**Comment by shazow** [comment]
Honestly a small typo is not very high priority, especially for a not-very-active project. I wouldn't hustle on it too hard.

**Comment by ricmoo** [comment]
Merged.

Thanks! :)

**Pull request closed without merging**
